### ISSUE TITLE
Version metadata issue when using Berkshelf

### ISSUE THREAD

**Issue by g3kk0** [berkshelf/berkshelf#1406]
Initially rasied as a cookbook problem (https://github.com/sethvargo/chef-sugar/issues/88) but now appears to be related to Berkshelf.

When declaring the version attribute within a cookbooks metadata like this:

```
require File.expand_path('../lib/chef/sugar/version', __FILE__)
version Chef::Sugar::VERSION
```

Berkshelf fails to interpret and returns the following error:

```
/home/mnewman/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- /home/mnewman/.berkshelf/cookbooks/chef-sugar-2.5.0/lib/chef/sugar/version (LoadError)
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/mnewman/.berkshelf/cookbooks/chef-sugar-2.5.0/metadata.rb:17:in `block in from_file'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/ridley-4.0.0/lib/ridley/mixin/from_file.rb:31:in `instance_eval'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/ridley-4.0.0/lib/ridley/mixin/from_file.rb:31:in `block in from_file'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/ridley-4.0.0/lib/ridley/mixin/from_file.rb:74:in `with_error_handling'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/ridley-4.0.0/lib/ridley/mixin/from_file.rb:30:in `from_file'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/ridley-4.0.0/lib/ridley/mixin/from_file.rb:5:in `from_file'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/ridley-4.0.0/lib/ridley/chef/cookbook.rb:38:in `from_path'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/cached_cookbook.rb:15:in `from_store_path'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/cookbook_store.rb:86:in `cookbook'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/cookbook_store.rb:67:in `import'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/cookbook_store.rb:30:in `import'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/installer.rb:102:in `install'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in `public_send'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in `dispatch'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:63:in `dispatch'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:60:in `block in invoke'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:71:in `block in task'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:362:in `block in task'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/tasks.rb:55:in `block in initialize'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
        from (celluloid):0:in `remote procedure call'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:92:in `value'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/pool_manager.rb:41:in `_send_'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/pool_manager.rb:123:in `method_missing'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in `public_send'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in `dispatch'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:63:in `dispatch'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:60:in `block in invoke'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:71:in `block in task'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:362:in `block in task'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/tasks.rb:55:in `block in initialize'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
        from (celluloid):0:in `remote procedure call'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/future.rb:104:in `value'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/future.rb:68:in `value'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/installer.rb:170:in `map'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/installer.rb:170:in `install_from_universe'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/installer.rb:39:in `run'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/berksfile.rb:371:in `install'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/berksfile.rb:590:in `vendor'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/cli.rb:387:in `vendor'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/cli.rb:52:in `dispatch'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/lib/berkshelf/cli.rb:27:in `execute!'
        from /home/mnewman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/berkshelf-3.1.3/bin/berks:5:in `<top (required)>'
        from /home/mnewman/.rbenv/versions/2.1.2/bin/berks:23:in `load'
        from /home/mnewman/.rbenv/versions/2.1.2/bin/berks:23:in `<main>'
```

```
# Berksfile
source 'http://berks-api.local'

metadata
```
```
# metadata.rb
depends 'chef-sugar'
```

**Comment by sethvargo** [comment]
Berkshelf should be preferring the metadata.json over the metadata.rb.

I also don't understand how you're even getting the metadata.rb because I never upload it to supermarket. It looks like you're using a local berkshelf api server - you should only upload the metadata.json for cookbooks.

**Comment by g3kk0** [comment]
We use gitmirror to sync directly from https://github.com/sethvargo/chef-sugar to our internal git repo (not pulling from Supermarket). Then we upload the cookbook to our Chef server with Knife. Berks-api then resolves dependencies using Chef server.

**Comment by reset** [comment]
@g3kk0 this isn't a Berkshelf problem. You're seeing this behaviour because you are uploading with Knife, which includes the raw `metadata.rb` file on upload, and then using a version of Chef-Client which doesn't prefer `metadata.json` over `metadata.rb`. I believe this was just fixed in Chef 12.

Sorry for your pain. I would use the `berks upload` command to upload your cookbooks or upgrade your Chef Client version.

**Comment by jorhett** [comment]
So this is still a problem with Berkshelf 4.3.5 and Chef 12.12.15 :(
