### ISSUE TITLE
Source :chef_server feature does not work as documented

### ISSUE THREAD

**Issue by dgarstang** [berkshelf/berkshelf#1541]
I've just downloaded the latest chefdk, 0.12. I'm trying to use my chef server as an artifact server for cookbooks which I believe is a new feature in berkshelf 4.3.0, which is in the chefdk 0.12.

The berkshelf documentation says:
``` If a source is configured with the location :chef_server, then Berkshelf will use the configured Chef Server as an API source. This requires Chef Server 12.4.0 or newer, or Hosted Chef.```

However, when I add the line source :chef_server to my Berksfile, and run 'berks install', it results in this error:

```/Users/doug/.chefdk/gem/ruby/2.1.0/gems/berkshelf-api-client-2.0.2/lib/berkshelf/api_client/chef_server_connection.rb:25:in `rescue in universe': undefined local variable or method `url' for #<Berkshelf::APIClient::ChefServerConnection:0x007f9abd17d248> (NameError)
	from /Users/doug/.chefdk/gem/ruby/2.1.0/gems/berkshelf-api-client-2.0.2/lib/berkshelf/api_client/chef_server_connection.rb:15:in `universe'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.0/lib/berkshelf/source.rb:49:in `build_universe'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.0/lib/berkshelf/installer.rb:21:in `block (2 levels) in build_universe'```

If I change the source line to be source 'source 'https://chef-dev.slicetest.com/organizations/slice' and run berks install again, I get:

```Error retrieving universe from source: https://chef-dev.slicetest.com/organizations/slice
  * [Berkshelf::APIClient::BadResponse] bad response #<Faraday::Response:0x007fbd2336e510 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:get @body="<html><body>You are being <a href=\"https://chef-dev.slicetest.com/login\">redirected</a>.</body></html>" @url=#<Addressable::URI:0x3fde919d0b98 URI:https://chef-dev.slicetest.com/organizations/slice/universe> @request=#<Faraday::RequestOptions timeout=30, open_timeout=30> @request_headers={"User-Agent"=>"Faraday v0.9.2"} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x007fbd2336e510 ...> @response_headers={"Server"=>"openresty/1.9.3.1", "Date"=>"Thu, 31 Mar 2016 19:34:46 GMT", "Content-Type"=>"text/html; charset=utf-8", "Transfer-Encoding"=>"chunked", "Connection"=>"keep-alive", "Status"=>"302 Found", "Strict-Transport-Security"=>"max-age=31536000", "X-Frame-Options"=>"DENY", "Content-Security-Policy"=>"default-src 'self'; connect-src 'self' https://munchkin.marketo.net http://munchkin-cdn.marketo.net https://munchkin-cdn.marketo.net http://.mktoresp.com https://.mktoresp.com http://scripts.demandbase.com https://scripts.demandbase.com http://api.demandbase.com https://api.demandbase.com http://b.company-target.com https://b.company-target.com; font-src 'self' themes.googleusercontent.com; frame-src 'self' http://scripts.demandbase.com https://scripts.demandbase.com http://api.demandbase.com https://api.demandbase.com http://b.company-target.com https://b.company-target.com; img-src 'self' https://ssl.google-analytics.com https://munchkin.marketo.net http://munchkin-cdn.marketo.net https://munchkin-cdn.marketo.net http://.mktoresp.com https://.mktoresp.com http://scripts.demandbase.com https://scripts.demandbase.com http://api.demandbase.com https://api.demandbase.com http://b.company-target.com https://b.company-target.com blob: data:; media-src 'none'; object-src 'none'; script-src 'self' https://ssl.google-analytics.com https://munchkin.marketo.net http://munchkin-cdn.marketo.net https://munchkin-cdn.marketo.net http://.mktoresp.com https://.mktoresp.com http://scripts.demandbase.com https://scripts.demandbase.com http://api.demandbase.com https://api.demandbase.com http://b.company-target.com https://b.company-target.com 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' fonts.googleapis.com;", "X-XSS-Protection"=>"1", "X-Content-Type-Options"=>"nosniff", "X-Download-Options"=>"noopen", "X-Permitted-Cross-Domain-Policies"=>"none", "Location"=>"https://chef-dev.slicetest.com/login", "Cache-Control"=>"no-cache", "Set-Cookie"=>"chef-manage=741db50b5a861324f4addd22702d84ba; path=/; secure; HttpOnly", "X-Request-Id"=>"276d138c-cefe-43f9-af76-aea761d20e80", "X-Runtime"=>"0.003421"} @status=302>>
Required artifacts do not exist at the desired version
Missing artifacts: slice-instance-scripts
Unable to find a solution for demands: nscd (= 1.0.1), slice-auditd (>= 0.0.0), slice-aws-ssm (>= 0.0.0), slice-awscli (>= 0.0.0), slice-base (2.0.24), slice-boot (>= 0.0.0), slice-bootstrap-node (>= 0.0.0), slice-chef-client (>= 0.0.0), slice-chef-handler (>= 0.0.0), slice-collectd (>= 0.0.0), slice-instance-scripts (>= 0.0.0), slice-ldap (>= 0.0.0), slice-motd (>= 0.0.0), slice-nrpe (>= 0.0.0), slice-ntp (>= 0.0.0), slice-openssh (>= 0.0.0), slice-ssh-keys (>= 0.0.0), slice-sudo (>= 0.0.0), slice-swap (>= 0.0.0), slice-sys-utils (>= 0.0.0)
```

**Comment by cheeseplus** [comment]
This was resolved by clearing out ~/.chefdk gems that were causing issues.

**Comment by reset** [comment]
@cheeseplus is this a solved issue then? Can we close?

**Comment by cheeseplus** [comment]
@reset please close - it's a non-issue

**Comment by reset** [comment]
@cheeseplus thanks!

**Comment by freimer** [comment]
I run into exactly the same issue, and I don't even have a ~/.chefdk directory.  I don't think it is solved, and I don't think it is a non-issue.

**Comment by cheeseplus** [comment]
@freimer in this case I know it was a non-issue as I resolved it in IRC - if you have an issue please open one with logs and details.

**Comment by miroswan** [comment]
I am experiencing this issue: 

```
Resolving cookbook dependencies...
Fetching 'test_cb' from source at .
Fetching cookbook index from https://trusty-standby.vagrant...
Fetching cookbook index from https://supermarket.chef.io...
Error retrieving universe from source: https://trusty-standby.vagrant
  * [Berkshelf::APIClient::ServiceNotFound] service not found at: https://trusty-standby.vagrant
Unable to satisfy the following requirements:

- `dummy (>= 0.0.0)` required by `user-specified dependency`
Unable to find a solution for demands: test_cb (0.1.0), dummy (>= 0.0.0)
```

```
knife cookbook list
dummy   0.1.0
```

**Comment by thommay** [comment]
@miroswan that doesn't look like the same issue, please don't add to year old tickets.
